name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      
env:
  # Customize the CMake build type here (Release, Debug, Distribution)
  BUILD_TYPE: Release
  VULKAN_VERSION: 1.3.224.1

jobs:
  linux-clang:
    runs-on: ubuntu-latest
    name: Linux Clang
    strategy:
      fail-fast: true
      matrix:
        build_type: [Release]
        
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: 3.27
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: ${{env.VULKAN_VERSION}}
        cache: true
    - name: Install GTK
      run: sudo apt install build-essential libgtk-3-dev
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_CXX_COMPILER=clang++
    - name: Build
      run: cmake --build ./build --config ${{env.BUILD_TYPE}}
    - name: "Release"
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ${{github.workspace}}/build/OxArena/Release/OxArena

  msvc_cl:
    runs-on: windows-latest
    name: Visual Studio CL
    strategy:
        fail-fast: true
        matrix:
            build_type: [Release]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: ${{env.VULKAN_VERSION}}
        cache: true
    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1.12.1
      with:
        arch: ${{ matrix.arch }}
        vsversion: 2022
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3
    - name: Configure CMake
      run: cmake -S . -B ${{github.workspace}}/build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: msbuild build\OxArena.sln /property:Configuration=${{env.BUILD_TYPE}}
    - name: "Release"
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Development Build"
        files: |
          ${{github.workspace}}\build\OxArena\Release\OxArena.exe

  #mac_clang:
  #  runs-on: macos-latest
  #  name: Mac Clang
  #  strategy:
  #      fail-fast: false
  #      matrix:
  #          build_type: [Release]
  #
  #  steps:
  #  - name: Checkout Code
  #    uses: actions/checkout@v3
  #    with:
  #      submodules: recursive
  #  - name: Install Vulkan SDK
  #    uses: humbletim/install-vulkan-sdk@v1.1.1
  #    with:
  #      version: ${{env.VULKAN_VERSION}}
  #      cache: true
  #  - name: Configure CMake
  #    run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
  #  - name: Build
  #    run: cmake --build ./build --config ${{env.BUILD_TYPE}}
  #  - name: "Release"
  #    uses: marvinpinto/action-automatic-releases@latest
  #    with:
  #      repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #      automatic_release_tag: "latest"
  #      prerelease: true
  #      title: "Development Build"
  #      files: |
  #        ${{github.workspace}}/build/OxArena/Release/OxArena

